backend:
  name: github
  repo: eyp-gr/website
  branch: Astro
  base_url: https://decap-proxy.odysseus-kirikopoulos.workers.dev

media_folder: "src/assets/blog"
public_folder: "/src/assets/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Cover Image", name: "image", widget: "image", required: false}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Attachment", name: "attachment", widget: "file", required: false}
  
  - name: "policies"
    label: "Policies"
    folder: "src/content/policies"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Cover Image", name: "image", widget: "image", required: false}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Attachment", name: "attachment", widget: "file", required: false}